### ISSUE TITLE
Click "Settings" will crash HTTP Toolkit

### ISSUE THREAD

**Issue by lupohan44** [Titoot/httptoolkit-interceptor#3]

**Comment by lupohan44** [comment]
### Oh no!
**Sorry, it's all gone wrong.**
TypeError: Cannot read properties of undefined (reading 'status') at kg.render (http://localhost:6969/app.js:3331:107) at ke (http://localhost:6969/vendors~main.bundle.js:16:9832) at http://localhost:6969/vendors~main.bundle.js:24:82914 at ue (http://localhost:6969/vendors~main.bundle.js:16:8016) at e.track (http://localhost:6969/vendors~main.bundle.js:16:19119) at kg.a [as render] (http://localhost:6969/vendors~main.bundle.js:24:82825) at kg.he (http://localhost:6969/vendors~main.bundle.js:24:83705) at h.render (http://localhost:6969/vendors~main.bundle.js:24:87252) at Pi (http://localhost:6969/vendors~main.bundle.js:482:69876) at Ri (http://localhost:6969/vendors~main.bundle.js:482:69671) at ws (http://localhost:6969/vendors~main.bundle.js:482:105470) at uc (http://localhost:6969/vendors~main.bundle.js:482:96717) at sc (http://localhost:6969/vendors~main.bundle.js:482:96642) at Xs (http://localhost:6969/vendors~main.bundle.js:482:93672) at http://localhost:6969/vendors~main.bundle.js:482:45314 at t.unstable_runWithPriority (http://localhost:6969/vendors~main.bundle.js:490:3844) at Yo (http://localhost:6969/vendors~main.bundle.js:482:45023) at Go (http://localhost:6969/vendors~main.bundle.js:482:45259) at Qo (http://localhost:6969/vendors~main.bundle.js:482:45194) at Vs (http://localhost:6969/vendors~main.bundle.js:482:90457) at Object.enqueueSetState (http://localhost:6969/vendors~main.bundle.js:482:48979) at y.setState (http://localhost:6969/vendors~main.bundle.js:474:1297) at http://localhost:6969/vendors~main.bundle.js:64:124588 at n (http://localhost:6969/vendors~main.bundle.js:64:15987

**Comment by Titoot** [comment]
I did know about this, the thing is the settings tab is related to the premium account (if i understand it correctly) , and since there's none it crashes

I could just disable the button or make it redirect to home, or just put mock data idk

Other than that all features work just fine

**Comment by Titoot** [comment]
@lupohan44 please use https://github.com/XielQs/httptoolkit-pro-patcher which is a better implementation from what I did.
